pool:
  vmImage: ubuntu-latest

stages:
- stage: Dev
  jobs:
  - job: Bicep
    steps:
    - task: AzureCLI@2
      displayName: 'Deploy resource group with Bicep'
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
         az --version
         az group create --name $(resourceGroupName) --location $(location)
         az deployment group create --resource-group $(resourceGroupName) --template-file ../infra/main.bicep